# install.packages("greta")
# install.packages("terra")
# install.packages("readxl")
# install.packages("dplyr")
# install.packages("tidyr")
# install.packages("scales")
# install.packages("tidyverse")
# install.packages("viridisLite")

library(greta)
library(DiagrammeR)
library(terra)
library(readxl)
library(dplyr)
library(malariaAtlas)
library(tidyr)
library(scales)
library(tidyverse)